module.exports = {
  STATUS: {
    SUCCESS: 'success',
    ERROR: 'error',
  },
  SUCCESS_MESSAGES: {
    REDIRECT_URL_GENERATED: 'RedirectURL has Generated',
    REPOSIRARY_FETCHED: 'All Repositaries Fetched',
    USER_DETIALS_FETCHED: 'User Details Fetched',
    OAUTH_INITIATED: 'VCS OAuth initiated successfully',
    TOKEN_EXCHANGED: 'Authorization code exchanged successfully',
    PROFILE_FETCHED: 'Integration profile fetched successfully',
    REPOS_FETCHED: 'VCS repositories fetched successfully',
    BRANCHES_FETCHED: 'VCS Branches fetched successfully',
    DEPLOYMENT_CREATED: 'Deployment Created',
    DEPLOYMENT_FETCHED: 'All deployment Settings fetched',
    DEPLOYMENT_FETCHED_GETALL: 'Deployments retrieved successfully',
    ZIP_UPLODED_SUCCESSFULLY: 'Zip file uploaded successfully',
  },
  ERROR_CODES: {
    // Gitlab
    MISSING_AUTH_CODE: 4001,
    USER_NOT_FOUND_CODE: 4004,
    TOKEN_EXCHANGE_FAILED_CODE: 4002,
    USER_ALREADY_EXISTS: 4020,
    REPOS_FETCH_FAILED_CODE: 4003,
    PROFILE_NOT_FOUND_CODE: 4004,
    DATABASE_ERROR_CODE: 4005,
    NO_REFRESH_TOKEN_CODE: 4006,
    REPO_ID_MISSING_CODE: 4017,
    INTERNAL_SERVER_ERROR_CODE: 500,
    KAFKA_PRODUCE_ERROR: 4017,
    GITHUB_OAUTH_ERROR: 4008,
    CODE_NOT_PROVIDED: 4009,
    NO_PORTALID: 4010,
    USER_NOT_FOUND: 4011,
    USER_ID_REQUIRED: 4012,
    TOKEN_EXCHANGE_FAILED: 4013,
    USER_PROFILE_ERROR: 4014,
    DB_ERROR: 4015,
    DEPLOYMENT_SETTINGS_NOTFOUND: 4016,
    NO_ACCESS_TOKEN: 4017,
    REPO_NAME_REQUIRED: 4018,
    DEPLOYMENTS_NOT_FOUND_CODE: 4021,

    DEPLOYMENT_FAILED: 4019,
    UNIQUE_CONSTRAINT_ERROR: 4020,

    FILE_ALREADY_EXISTS_CODE: 4021,
  },
  ERROR_MESSAGES: {
    GITHUB_OAUTH_FAILED: 'Error in initiating VCS OAuth',
    CODE_NOT_PROVIDED: 'No code provided',
    USER_NOT_FOUND: 'User not found',
    USER_ID_REQUIRED: 'User ID is required.',
    USER_PROFILE_ERROR: 'User profile not found.',
    DATABASE_ERROR: 'Database error',
    DEPLOYMENT_SETINGS_NOTFOUND: 'Deployment Settings Not found.',
    KAFKA_PRODUCE_ERROR: 'Kaka Producing Error',
    NOT_FOUND_ERROR: 'Not Found Error',

    // gitlab
    DEPLOYMENT_SETTINGS_NOTFOUND: 'Deployment Settings Not found.',
    DEPLOYMENTS_NOT_FOUND: 'Deployments Not found.',
    NO_ACCESS_TOKEN: 'No access token provided',
    MISSING_AUTH_CODE: 'Authorization code is required',
    TOKEN_EXCHANGE_FAILED: 'Failed to exchange authorization code for token',
    REPOS_FETCH_FAILED: 'Failed to fetch repositories from VCS',
    PROFILE_NOT_FOUND: ' Profile not found',
    NO_REFRESH_TOKEN: 'No refresh token available',
    INTERNAL_SERVER_ERROR: 'Internal Server Error',
    REPO_ID_MISSING: 'Repository ID is missing',
    USER_ALREADY_EXISTS: 'User Details Already Exists',
    DEPLOYMENT_FAILED: 'Failed to deployment Details in DB',
    UNIQUE_CONSTRAINT_ERROR: 'A deployment with this name in already exists in the specified environment',
    CONSTRAINT_ERROR: 'A Deployment with this Environment Id does not exists.',
    ENVIRONMENT_ID_REQUIRED: 'EnvironmentId is required',
    FILE_ALREADY_EXISTS: 'File already exists in S3. Choose a different file name.',
    FILE_NOT_FOUND: 'NotFound',
    FILE_UPLOAD_ERROR: 'File upload error',
    VALIDATION_ERROR: 'Validation error',
  },
  HTTP_STATUS: {
    NOT_FOUND: 404,
    INTERNAL_SERVER_ERROR: 500,
    BAD_REQUEST: 400,
    OAUTH_INITIATED: 'GitLab OAuth initiated successfully',
    TOKEN_EXCHANGED: 'Authorization code exchanged successfully',
    PROFILE_FETCHED: 'GitLab profile fetched successfully',
    REPOS_FETCHED: 'GitLab repositories fetched successfully',
    UNAUTHORIZED: 401,
    SEQUELIZE_CONSTRAINT_ERROR: 'SequelizeUniqueConstraintError',
  },
};
